### ISSUE TITLE
unpickling issue

### ISSUE THREAD

**Issue by cclark1e** [abelavit/PepCNN#1]
Hi, what version of pandas/pickle was used to pickle the dat files?

I'm getting the issue AttributeError: Can't get attribute '_unpickle_block' from the positive_set = pickle.load(file) line and I believe the issue is due to a version mismatch, but I'm not sure which version i should update/revert to.

Thank you!

**Comment by abelavit** [comment]
Hi. The versions of pandas and pickle I used are:

Pandas ver1.5.3
Pickle ver4.0

Thank you.
