### ISSUE TITLE
q

### ISSUE THREAD

**Issue by JNU-luyi** [abelavit/PepCNN#2]
Hello, when building the PSSM matrix, I first create a database (DB), then use BLAST for sequence alignment. However, during the process of generating the PSSM, there are always some proteins for which I am unable to create the PSSM. May I ask what database you used for the alignment?

**Comment by abelavit** [comment]
Hello. To generate PSSM, we run PSI-BLAST against non-redundant protein database (NR) which can be found from: 

[https://ftp.ncbi.nlm.nih.gov/blast/db/](https://protect-au.mimecast.com/s/Cq4fCq7BwVcOxOJvwsZ85qo?domain=ftp.ncbi.nlm.nih.gov/)

[https://www.ncbi.nlm.nih.gov/books/NBK62345/#blast_ftp_site.The_blastdb_subdirectory](https://protect-au.mimecast.com/s/JVTfCr8DyEHAzA4OJIzRP_S?domain=ncbi.nlm.nih.gov)

It is a huge protein database. Using NR, we usually can generate PSSM for every protein. If PSIBLAST does not find any alignment to calculate PSSM, it just returns the BLOSUM62 scores (static substitution score) for every amino acids. Sometimes, when the proteins are short (also short peptides), it does not generate any pssm. In this case, we manually generate PSSM by just putting the BLOSUM values for each amino acid.
