### ISSUE TITLE
run

### ISSUE THREAD

**Issue by swerty123** [abelavit/PepCNN#3]
Hello, I was wondering, after downloading the data in the link, how can I train the model by running dataset1_PepCNN_train.py? I don't see any code part in this file. If you can answer me, thank you very much

**Comment by abelavit** [comment]
Hi, the dataset1_PepCNN_train.py file imports the two python scripts called dataset1_num1_extraction_of_samples and dataset1_num2_train_network. Please download all those files into the same directory and then run the dataset1_PepCNN_train.py file.

**Comment by swerty123** [comment]
ohhhhhh，thank you！！!
