### ISSUE TITLE
feature extraction

### ISSUE THREAD

**Issue by heihno** [abelavit/PepCNN#4]
Hello author, I'm a beginner, I can't understand the part of feature extraction, can you share the detailed process and code? Thank you so much.

**Comment by abelavit** [comment]
Thank you for the question. I have now added Fasta.txt file that contains all the protein sequences used in this work. This file can be used to extract each of the features. For instance, the Fasta file can be used to extract ProtT5 embedding from https://github.com/agemagician/ProtTrans

**Comment by heihno** [comment]
Thank you!!!I'll take a good look at it.

**Comment by heihno** [comment]
Hello author，would you like to ask if you can provide the code that uses the RF classifier to select the feature combination?
