### ISSUE TITLE
Request for a short inference script

### ISSUE THREAD

**Issue by luukhd2** [abelavit/PepCNN#6]
Could you provide me with a short inference script that predicts binding for custom data? One that can be ran without downloading the full datasets or retraining the model. 

I noticed the original input was a .tsv file:
`https://github.com/abelavit/PepCNN/blob/main/dataset1_num1_extraction_of_samples.py#L47`

My input is in the form of a:
- protein sequence
- peptide sequence

Thank you in advance for any help

**Comment by abelavit** [comment]
Thank you for reaching out. 

Our current work is limited to only showing the potential of the method on the test sets 1 and 2. In future, we hope to propose a more accurate model and with the option to allow the query of new protein sequences to predict binding sites.
